apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    app: ui
    rel: stable
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
